USE HOTELES;

SELECT * FROM HABITACION;
SELECT * FROM VISTA;
SELECT * FROM EDIFICIO;
SELECT * FROM TIPOHABITACION;
SELECT * FROM ESTATUS;
SELECT * FROM RESERVACION_DETALLE;
SELECT * FROM RESERVACION;
SELECT * FROM ESTATUSRESERVACION;
SELECT * FROM CORREO;
SELECT * FROM TIPOCORREO;
SELECT * FROM TELEFONO;
SELECT * FROM TIPOTELEFONO;
SELECT * FROM CLIENTE;
SELECT * FROM USUARIO;
SELECT * FROM ROL;