CREATE DATABASE HOTELES;

USE HOTELES;

CREATE TABLE ROL (
	IdRol INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  Descrip VARCHAR(45) NOT NULL
);

CREATE TABLE ESTATUSRESERVACION (
	IdEstatusReservacion INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Descrip	VARCHAR(45) NOT NULL
);

CREATE TABLE ESTATUS (
	IdEstatus INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Descrip	VARCHAR(45) NOT NULL 
);

CREATE TABLE TIPOCORREO (
	IdTipoCorreo INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  Descrip VARCHAR(45) NOT NULL
);

CREATE TABLE TIPOHABITACION (
	IdTipoHabitacion INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Descrip	VARCHAR(60) NOT NULL,
	Precio DECIMAL (12,2) NOT NULL,
	Capacidad INT NOT NULL
);

CREATE TABLE TIPOTELEFONO (
	IdTipoTelefono INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  Descrip VARCHAR(45) NOT NULL
);

CREATE TABLE EDIFICIO (
	IdEdificio INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Descrip	VARCHAR(45) NOT NULL,
	Niveles INT NOT NULL
);

CREATE TABLE VISTA (
	IdVista INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Descrip VARCHAR(45) NOT NULL
);

CREATE TABLE USUARIO (
	IdUsuario INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  Usuario VARCHAR(45) NOT NULL,
  Contra VARCHAR(45) NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  APaterno VARCHAR(50) NOT NULL,
  AMaterno VARCHAR(50) NOT NULL,
  IdRol INT NOT NULL,
  FOREIGN KEY (IdRol) REFERENCES ROL(IdRol)
);

CREATE TABLE CLIENTE (
	IdCliente INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
  Nombre VARCHAR(45) NOT NULL,
  APaterno VARCHAR(60) NOT NULL,
  AMaterno VARCHAR(60) NOT NULL,
  IdUsuario INT NOT NULL,
  FecRegistro DATE NOT NULL,
  FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario)
);

CREATE TABLE TELEFONO (
	IdTelefono INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  IdCliente INT NOT NULL,
  Numero VARCHAR(45) NOT NULL,
  IdTipoTelefono INT NOT NULL,
  FOREIGN KEY (IdTipoTelefono) REFERENCES TIPOTELEFONO(IdTipoTelefono)
);

CREATE TABLE CORREO (
	IdCorreo INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  IdCliente INT NOT NULL,
  Correo VARCHAR(45) NOT NULL,
  IdTipoCorreo INT NOT NULL,
  FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente),
  FOREIGN KEY (IdTipoCorreo) REFERENCES TIPOCORREO(IdTipoCorreo)
);

CREATE TABLE HABITACION (
	IdHabitacion INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Descrip VARCHAR(45) NOT NULL,
	Nivel INT NOT NULL,
	IdTipoHabitacion INT NOT NULL,
	IdEdificio INT NOT NULL,
	IdVista INT NOT NULL,
	IdEstatus INT NOT NULL,
  FOREIGN KEY (IdTipoHabitacion) REFERENCES TIPOHABITACION(IdTipoHabitacion),
  FOREIGN KEY (IdEdificio) REFERENCES EDIFICIO(IdEdificio),
  FOREIGN KEY (IdVista) REFERENCES VISTA(IdVista),
  FOREIGN KEY (IdEstatus) REFERENCES ESTATUS(IdEstatus)
);

CREATE TABLE RESERVACION (
	IdReservacion INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  IdUsuario INT NOT NULL,
  IdCliente INT NOT NULL,
  IdHabitacion INT NOT NULL,
  FecInicio DATE NOT NULL,
  FecFin DATE NOT NULL,
  Monto DECIMAL(12,2) NOT NULL,
  FecRegistro DATETIME NOT NULL,
  IdEstatusReservacion INT NOT NULL,
  FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario),
  FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente),
  FOREIGN KEY (IdHabitacion) REFERENCES HABITACION(IdHabitacion),
  FOREIGN KEY (IdEstatusReservacion) REFERENCES ESTATUSRESERVACION(IdEstatusReservacion)
);

CREATE TABLE RESERVACION_DETALLE (
	IdReservacionDetalle INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	IdReservacion INT NOT NULL,
  IdCliente INT NOT NULL,
  FecIN DATETIME NOT NULL,
  FecOUT DATETIME NOT NULL,
  FOREIGN KEY (IdReservacion) REFERENCES RESERVACION(IdReservacion),
  FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente)
);